# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZoJRre_zpLkQYylOlg7JAQgamH6ydrzC
"""

!pip install -q huggingface_hub

from huggingface_hub import hf_hub_download

file1 = hf_hub_download(
    repo_id="huggan/wikiart",
    filename="data/train-00000-of-00072.parquet",
    repo_type="dataset"
)

file2 = hf_hub_download(
    repo_id="huggan/wikiart",
    filename="data/train-00001-of-00072.parquet",
    repo_type="dataset"
)
file3 = hf_hub_download(
    repo_id="huggan/wikiart",
    filename="data/train-00002-of-00072.parquet",
    repo_type="dataset"
)

file4 = hf_hub_download(
    repo_id="huggan/wikiart",
    filename="data/train-00004-of-00072.parquet",
    repo_type="dataset"
)
print(file3)
print(file4)

for f in [file1, file2,file3,file4 ]:
    with open(f, "rb") as file:
        start = file.read(4)

    with open(f, "rb") as file:
        file.seek(-4, 2)
        end = file.read(4)

    print(f)
    print("START:", start)
    print("END:", end)

import pandas as pd

df1 = pd.read_parquet(file1)
df2 = pd.read_parquet(file2)
df3 = pd.read_parquet(file3)
df4 = pd.read_parquet(file4)

df = pd.concat([df1, df2, df3,df4], ignore_index=True)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns)

display(df.head())

from datasets import load_dataset_builder

builder = load_dataset_builder("huggan/wikiart")
features = builder.info.features

print(features)

df["artist_name"] = df["artist"].apply(
    lambda x: features["artist"].int2str(x)
)

df["genre_name"] = df["genre"].apply(
    lambda x: features["genre"].int2str(x)
)

df["style_name"] = df["style"].apply(
    lambda x: features["style"].int2str(x)
)

display(
    df[["artist_name", "genre_name", "style_name"]].head(10)
)

print(df["style_name"].value_counts())

print("Unique artists:", df["artist_name"].nunique())

print(df["artist_name"].value_counts().head(20))

SHARED_STYLES = [
    "Realism",
    "Baroque",
    "Romanticism",
    "Rococo"
]

wikiart_shared = df[
    df["style_name"].isin(SHARED_STYLES)
]

print(wikiart_shared["style_name"].value_counts())

print(df["style_name"].value_counts())

import pandas as pd
import pyarrow.parquet as pq
from huggingface_hub import HfFileSystem

fs = HfFileSystem()
files = sorted(fs.glob("datasets/huggan/wikiart/data/*.parquet"))
print(len(files), "files")

parts = []
for i, f in enumerate(files, 1):
    with fs.open(f, "rb") as fh:
        parts.append(pq.read_table(fh, columns=["artist", "genre", "style"]).to_pandas())
    print(i, "/", len(files))

labels = pd.concat(parts, ignore_index=True)

# numbers -> names (uses the 'features' you already loaded)
for c in ["artist", "genre", "style"]:
    labels[c] = labels[c].apply(features[c].int2str)

labels.to_csv("wikiart_labels.csv", index=False)
print("Total images:", len(labels))
print("Artists:", labels["artist"].nunique())
print(labels["style"].value_counts())

pip install imagehash

# Commented out IPython magic to ensure Python compatibility.
"""
color_baseline_10styles.py
Color-only baseline on the new 10-style WikiArt (huggan/wikiart).

Same idea as the first baseline (logistic regression on 32 color features,
class-weighted, 70/15/15, seed 42), but:
  - 10 styles instead of 13 (chance = 10%)
  - runs TWICE: random split vs artist-disjoint split
  - also reports top-3 accuracy and majority floor
  - cleans the sample first: broken files, duplicates, conflicting labels,
    and flags black-and-white images (cleaning_report.csv)

Run in Colab:
  !pip install -q huggingface_hub pyarrow scikit-learn pillow pandas matplotlib datasets imagehash
#   %run color_baseline_10styles.py
It reads only the sampled images, one parquet file at a time.
"""
import io, json, os, random
import numpy as np
import pyarrow.parquet as pq
from PIL import Image
import imagehash
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split, StratifiedGroupKFold
from sklearn.metrics import accuracy_score, f1_score, top_k_accuracy_score, classification_report

REPO = "huggan/wikiart"
PER_STYLE = 300          # images per style (3,000 total), same size as before
SEED = 42
OUT = "baseline_10styles"
STYLES = ["Early_Renaissance", "High_Renaissance", "Northern_Renaissance",
          "Mannerism_Late_Renaissance", "Baroque", "Rococo", "Romanticism",
          "Realism", "Impressionism", "Post_Impressionism"]


# ---------------------------------------------------------------- data access
def list_files():
    from huggingface_hub import HfFileSystem
    fs = HfFileSystem()
    return fs, sorted(fs.glob(f"datasets/{REPO}/data/*.parquet"))


def style_names():
    from datasets import load_dataset_builder
    feats = load_dataset_builder(REPO).info.features
    return feats["style"].names, feats["artist"].names


# ---------------------------------------------------------------- features
def image_checks(img_bytes):
    """Perceptual hash (finds near-identical images) and a black-and-white flag."""
    img = Image.open(io.BytesIO(img_bytes)).convert("RGB")
    img.thumbnail((256, 256))
    sat = np.asarray(img.convert("HSV"), dtype=np.float32)[..., 1] / 255.0
    return str(imagehash.phash(img)), bool(sat.mean() < 0.05)


def color_features(img_bytes):
    """32 color features: RGB+HSV mean/std (12), hue hist (12), sat hist (4), value hist (4)."""
    img = Image.open(io.BytesIO(img_bytes)).convert("RGB")
    img.thumbnail((128, 128))
    rgb = np.asarray(img, dtype=np.float32) / 255.0
    hsv = np.asarray(img.convert("HSV"), dtype=np.float32) / 255.0
    px_rgb, px_hsv = rgb.reshape(-1, 3), hsv.reshape(-1, 3)
    stats = np.concatenate([px_rgb.mean(0), px_rgb.std(0), px_hsv.mean(0), px_hsv.std(0)])
    h = np.histogram(px_hsv[:, 0], bins=12, range=(0, 1))[0]
    s = np.histogram(px_hsv[:, 1], bins=4, range=(0, 1))[0]
    v = np.histogram(px_hsv[:, 2], bins=4, range=(0, 1))[0]
    n = len(px_hsv)
    return np.concatenate([stats, h / n, s / n, v / n])


# ---------------------------------------------------------------- sampling
def sample_rows(fs, files, style_list):
    """Reads only the style/artist columns to pick PER_STYLE random rows per style."""
    parts, offset = [], 0
    for f in files:
        with fs.open(f, "rb") as fh:
            t = pq.read_table(fh, columns=["artist", "style"]).to_pandas()
        t["file"], t["local"] = f, np.arange(len(t))
        parts.append(t)
    lab = pd.concat(parts, ignore_index=True)
    lab["style_name"] = lab["style"].map(lambda i: style_list[i])
    lab = lab[lab["style_name"].isin(STYLES)]
    return pd.concat([g.sample(min(PER_STYLE, len(g)), random_state=SEED)
                      for _, g in lab.groupby("style_name")])


def extract(fs, sample):
    """Opens each file once and reads only the row groups that hold sampled rows."""
    feats, keep, hashes, gray, broken = [], [], [], [], 0
    for k, (f, g) in enumerate(sample.groupby("file"), 1):
        with fs.open(f, "rb") as fh:
            pf = pq.ParquetFile(fh)
            starts = np.cumsum([0] + [pf.metadata.row_group(i).num_rows
                                      for i in range(pf.num_row_groups)])
            wanted = set(g["local"])
            for rg in range(pf.num_row_groups):
                rows = [r for r in wanted if starts[rg] <= r < starts[rg + 1]]
                if not rows:
                    continue
                col = pf.read_row_group(rg, columns=["image"]).column("image").to_pylist()
                for r in rows:
                    try:
                        b = col[r - starts[rg]]["bytes"]
                        f_ = color_features(b)
                        h_, bw_ = image_checks(b)
                    except Exception as e:
                        broken += 1
                        if broken <= 3:
                            print(f"  image failed: {type(e).__name__}: {e}")
                        continue
                    feats.append(f_); hashes.append(h_); gray.append(bw_)
                    keep.append(g.index[g["local"] == r][0])
        print(f"  file {k}/{sample['file'].nunique()} done, {len(feats)} images so far")
        if k == 1 and not feats:
            raise RuntimeError("Every image in the first file failed. See the error above and fix it first.")
    out = sample.loc[keep].copy()
    out["phash"], out["grayscale"] = hashes, gray
    return np.vstack(feats), out, broken


def clean(X, sample, broken):
    """Removes duplicates. Same style: keep one copy. Different styles: drop all copies."""
    n0 = len(sample)
    sample = sample.reset_index(drop=True)
    drop = set()
    dup_same = dup_conflict = 0
    for h, g in sample.groupby("phash"):
        if len(g) < 2:
            continue
        if g["style_name"].nunique() == 1:
            drop.update(g.index[1:]); dup_same += len(g) - 1
        else:
            drop.update(g.index); dup_conflict += len(g)
    keep = np.array([i for i in range(len(sample)) if i not in drop], dtype=int)
    report = pd.DataFrame([
        ("sampled", n0 + broken),
        ("broken files removed", broken),
        ("duplicate copies removed (same style)", dup_same),
        ("images removed (duplicates with different styles)", dup_conflict),
        ("black-and-white images (kept, flagged)", int(sample["grayscale"].sum())),
        ("final images", len(keep)),
    ], columns=["step", "images"])
    return X[keep], sample.loc[keep], report


# ---------------------------------------------------------------- evaluation
def evaluate(name, Xtr, ytr, Xte, yte, classes):
    model = make_pipeline(StandardScaler(),
                          LogisticRegression(max_iter=3000, class_weight="balanced"))
    model.fit(Xtr, ytr)
    pred, proba = model.predict(Xte), model.predict_proba(Xte)
    majority = pd.Series(ytr).value_counts().idxmax()
    res = {
        "split": name,
        "n_train": int(len(ytr)), "n_test": int(len(yte)),
        "accuracy": round(accuracy_score(yte, pred), 3),
        "top3_accuracy": round(top_k_accuracy_score(yte, proba, k=3, labels=model.classes_), 3),
        "macro_f1": round(f1_score(yte, pred, average="macro"), 3),
        "chance": round(1 / len(classes), 3),
        "majority_floor": round(float(np.mean(np.array(yte) == majority)), 3),
    }
    rep = classification_report(yte, pred, output_dict=True, zero_division=0)
    per_style = {c: round(rep[c]["f1-score"], 3) for c in classes if c in rep}
    return res, per_style


def split_random(y):
    idx = np.arange(len(y))
    tr, tmp = train_test_split(idx, test_size=0.30, stratify=y, random_state=SEED)
    va, te = train_test_split(tmp, test_size=0.50, stratify=y[tmp], random_state=SEED)
    return tr, va, te


def split_artist(y, groups):
    """About 70/15/15, and every artist is in only one part."""
    folds = list(StratifiedGroupKFold(n_splits=7, shuffle=True, random_state=SEED).split(y, y, groups))
    te, va = folds[0][1], folds[1][1]
    tr = np.setdiff1d(np.arange(len(y)), np.concatenate([te, va]))
    return tr, va, te


def main():
    random.seed(SEED); np.random.seed(SEED)
    os.makedirs(OUT, exist_ok=True)
    style_list, artist_list = style_names()
    fs, files = list_files()
    print(f"{len(files)} parquet files")

    print("Picking the sample (labels only) ...")
    sample = sample_rows(fs, files, style_list)
    print(sample["style_name"].value_counts().to_string())

    print("Extracting color features ...")
    X, sample, broken = extract(fs, sample)

    print("Cleaning ...")
    X, sample, report = clean(X, sample, broken)
    report.to_csv(f"{OUT}/cleaning_report.csv", index=False)
    print(report.to_string(index=False))
    print("Black-and-white images per style:")
    print(sample.groupby("style_name")["grayscale"].sum().to_string())

    y = sample["style_name"].to_numpy()
    artist = sample["artist"].map(lambda i: artist_list[i]).to_numpy()
    # each 'Unknown Artist' image is its own group, so it can't link train and test
    groups = np.where(artist == "Unknown Artist",
                      ["unknown_" + str(i) for i in sample.index], artist)
    np.savez(f"{OUT}/features.npz", X=X, y=y, artist=artist, grayscale=sample["grayscale"].to_numpy())
    unknown_share = float(np.mean(artist == "Unknown Artist"))

    results, per_style = [], {}
    for name, (tr, va, te) in [("random", split_random(y)),
                               ("artist-disjoint", split_artist(y, groups))]:
        r, ps = evaluate(name, X[tr], y[tr], X[te], y[te], STYLES)
        rv, _ = evaluate(name, X[tr], y[tr], X[va], y[va], STYLES)
        r["val_accuracy"] = rv["accuracy"]
        results.append(r); per_style[name] = ps
        print(f"\n{name}: acc {r['accuracy']}  top-3 {r['top3_accuracy']}  "
              f"macro F1 {r['macro_f1']}  (chance {r['chance']}, majority {r['majority_floor']}, "
              f"val acc {r['val_accuracy']})")

    pd.DataFrame(results).to_csv(f"{OUT}/results.csv", index=False)
    pd.DataFrame(per_style).rename_axis("style").to_csv(f"{OUT}/per_style_f1.csv")
    with open(f"{OUT}/summary.json", "w") as fh:
        json.dump({"per_style": PER_STYLE, "seed": SEED, "unknown_artist_share": round(unknown_share, 3),
                   "results": results}, fh, indent=2)

    try:
        import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
        ps = pd.DataFrame(per_style).sort_values("random")
        ps.plot.barh(figsize=(8, 5), color=["#7A1F3D", "#C9A227"])
        plt.xlabel("F1 score (test set)"); plt.title("Color-only baseline, 10 styles")
        plt.tight_layout(); plt.savefig(f"{OUT}/per_style_f1.png", dpi=150); plt.close()
    except Exception as e:
        print("chart skipped:", e)

    print(f"\nUnknown Artist share in this sample: {unknown_share:.1%}")
    print(pd.DataFrame(results).to_string(index=False))
    print(f"\nFiles saved in ./{OUT}/")


if __name__ == "__main__":
    main()
